config/routes.rb
Rails.application.routes.draw do
    root 'top#main'
    get 'top/main'
    resources :products
    resources :cart_items, only:[:create,:destroy]
    resources :carts, only:[:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
      def current_cart
          if session[:cart_id]
              @cart = Cart.find(session[:cart_id])
          else
              @cart = Cart.create
              session[:cart_id] = @cart.id
          end
          @cart
      end
      helper_method :current_cart
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
    def create
        if @cart_item.blank?
           @cart_item = current_cart.build(product_id: params[:product_id])
        end
      
        @cart_item.save
        redirect_to current_cart
    end
    def destroy
        cart_item = CartItem.find(params[:id])
        cart_item.destroy
        redirect_to current_cart
    end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def show
        @cart_items = current_cart
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @products = Product.all
    end
    
    def new
        @product = Product.new
    end
    
    def create
        @product = Product.new(name: params[:product][:name], price: params[:product][:price])
        if @product.save
            
            flash[:success] = "登録完了"
            redirect_to root_path
        else
            flash[:failed] = "登録失敗"
            render 'new'
        end
    end
    
    def destroy
        product = Product.find(params[:id])
        product.destroy
           
        redirect_to products_path, flash: {destroy:  "ツイートを削除しました。"}
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/carts/show.html.erb
<h2>カート</h2>
<table>
	<tr>
		<th>商品名</th>
		<th>価格</th>
		<th>数量</th>
	</tr>
	<% if @products.present? %>
		<% @cart_items.each do |item| %>
		<tr>
			<td text-align:center;><font size="4"><%= item.product.name %></font></td>
			<td text-align:center;><font size="4"><%= (item.product.price).to_i %>円</font></td>
            <td></td>
            <td><%= link_to '削除', item, method: :delete %></td>
		</tr>
		<% end %>
	<% end %>
</table>


<%= link_to '戻る', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h2>商品一覧</h2>
<table>
	<% @products.each do |good| %>
	<tr>
		<td>
			<p><font size="5">商品名：<%= good.name %></font></p>
			<p><font size="4">価格：<%= good.price %>円</font></p>
		</td>
		<td>
			<%= button_to 'カートに入れる', cart_items_path(product_id: good), class: 'fbtn' %>
			<%= link_to '削除', good, method: :delete %>
		</td>
	</tr>

	<% end %>
</table>


<%= link_to "商品登録", new_product_path %>
<%= link_to "戻る", root_path %>

app/views/products/new.html.erb
<h2>新商品登録</h2>
<%= form_for @product do |form| %>
 <%= form.label :name, "商品名" %>
 <%= form.text_field :name %>
 <%= form.label :price, "価格" %>
 <%= form.text_field :price %>
 <%= form.submit "登録" %>
<% end %>

<%= link_to 'Back', root_path %>

app/views/top/main.html.erb
<% if flash[:info] %>
<%= flash[:info] %>
<% end %>

<% if @products.present? %>
<% @products.each do |e| %>
<p>
    <%= form_tag cart_items_path, method: :post do %>
    <%= e.name %>
    <%= e.price %>円
    <%= hidden_field_tag :product_id, e.id%>
    数量：<%= select_tag(:qty, options_for_select((1..30)))%>
    <%= submit_tag'カートへ追加する'%>
    <% end %>
</p>
<% end %>
<% end %>
<p><%= link_to 'カートの中身を見る', cart_path(current_cart.id) %></p>

<p><%= link_to '商品一覧', products_path %></p>